In [1]:
import pandas as pd

In [13]:
import os

# get current working directory
current_dir = os.getcwd()

# move up one level to parent directory
os.chdir("..")

# move to "data" directory
os.chdir("data")

# confirm new working directory
data_dir = os.getcwd()

files = pd.DataFrame.from_dict({"file": []})


for file in os.listdir(data_dir):
    df = pd.read_csv(file)
    columns = df.columns

    for column in columns:
        if column not in files.columns:
            files[column] = 0

    # Add a new row to the dataframe with the name of the file and 1 for each column
    # that exists in the file and a 0 for each column that does not exist in the file
    files = pd.concat(
        [
            files,
            pd.DataFrame.from_dict(
                {"file": [file], **{column: 1 for column in columns}}
            ),
        ],
        ignore_index=True,
    )

files

,file,gender,forecast_date,playin_flag,rd1_win,rd2_win,rd3_win,rd4_win,rd5_win,rd6_win,rd7_win,team_alive,team_id,team_name,team_rating,team_region,team_seed,results_to,team_slot
0,fivethirtyeight_2017.csv,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0
1,fivethirtyeight_2018.csv,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0
2,fivethirtyeight_2019.csv,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
3,fivethirtyeight_2021.csv,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
4,fivethirtyeight_2022.csv,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1